#
# This OCPI HDL primitive library was created from the pcore located at
# Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_sys_reset_v3_00_a
#
# Used OCPI's simple rules for creating this library:
# 1) Created the package file proc_sys_reset_v3_00_a_pkg.vhd 
# and declared only the top component of the pcore, "proc_sys_reset".
# 2) Per the framework, the lone package will be built first and then 
# the other source modules. I.e, there's no need to explicitly assign SourceFiles.

OnlyTargets=spartan6 isim xsim

include $(OCPI_CDK_DIR)/include/hdl/hdl-lib.mk
