# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

# Surprised that this was necessary
#Cores=\
	../../platforms/mpcie/target-spartan6/mpcie_rv_blk_mem_gen_v7_3_1.ngc \
	../../platforms/mpcie/target-spartan6/mpcie_rv_blk_mem_gen_v7_3_2.ngc \
	../../platforms/mpcie/target-spartan6/mpcie_rv_blk_mem_gen_v7_3_3.ngc \
	../../platforms/mpcie/target-spartan6/mpcie_rv_fifo_generator_v9_3_1.ngc \
	../../platforms/mpcie/target-spartan6/mpcie_rv_fifo_generator_v9_3_2.ngc \
	../../platforms/mpcie/target-spartan6/mpcie_rv_fifo_generator_v9_3_3.ngc

include $(OCPI_CDK_DIR)/include/hdl/hdl-assembly.mk
