#
# This OCPI HDL primitive library was created from the pcore located at
# Xilinx/14.7/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/
#
# Used OCPI's rules for creating this library:
# 1) All Package and Body modules must contain _pkg.vhd or _body.vhd, respectively.
# Therefore, the following files were renamed:
# - family.vhd to family_pkg.vhd
# - family_support.vhd to family_support_pkg.vhd
# Additionally, the following package was renamed to match the Library Name
# - proc_common_pkg.vhd to proc_common_v3_00_a_pkg.vhd
# Note: The original package files remain in this directory, but are not built per 2)
# 2) Per the framework, since there are multiple package files and some
# originally named files remain in this directory, the SourceFiles is used
# to specify the build order and to exclude unwanted files from the build.

OnlyTargets=spartan6 isim xsim
SourceFiles=\
  proc_common_v3_00_a_pkg.vhd \
  family_pkg.vhd \
  family_support_pkg.vhd \
  coregen_comp_defs.vhd \
  common_types_pkg.vhd \
  conv_funs_pkg.vhd \
  ipif_pkg.vhd \
  async_fifo_fg.vhd \
  sync_fifo_fg.vhd \
  basic_sfifo_fg.vhd \
  blk_mem_gen_wrapper.vhd \
  addsub.vhd \
  counter_bit.vhd \
  counter.vhd \
  direct_path_cntr.vhd \
  direct_path_cntr_ai.vhd \
  down_counter.vhd \
  eval_timer.vhd \
  inferred_lut4.vhd \
  ipif_steer.vhd \
  ipif_steer128.vhd \
  ipif_mirror128.vhd \
  ld_arith_reg.vhd \
  ld_arith_reg2.vhd \
  mux_onehot.vhd \
  or_bits.vhd \
  or_muxcy.vhd \
  or_gate.vhd \
  or_gate128.vhd \
  pf_adder_bit.vhd \
  pf_adder.vhd \
  pf_counter_bit.vhd \
  pf_counter.vhd \
  pf_counter_top.vhd \
  pf_occ_counter.vhd \
  pf_occ_counter_top.vhd \
  pf_dpram_select.vhd \
  pselect.vhd \
  pselect_mask.vhd \
  srl16_fifo.vhd \
  srl_fifo.vhd \
  srl_fifo2.vhd \
  srl_fifo3.vhd \
  srl_fifo_rbu.vhd \
  valid_be.vhd \
  or_with_enable_f.vhd \
  muxf_struct_f.vhd \
  cntr_incr_decr_addn_f.vhd \
  dynshreg_f.vhd \
  dynshreg_i_f.vhd \
  mux_onehot_f.vhd \
  srl_fifo_rbu_f.vhd \
  srl_fifo_f.vhd \
  compare_vectors_f.vhd \
  pselect_f.vhd \
  counter_f.vhd \
  or_muxcy_f.vhd \
  or_gate_f.vhd \
  soft_reset.vhd

include $(OCPI_CDK_DIR)/include/hdl/hdl-lib.mk
